export const locaties = [
  { slug: "venlo",   naam: "Venlo",   buurt: ["Tegelen","Blerick","Belfeld","Veegtes","Noorderpoort"] },
  { slug: "tegelen", naam: "Tegelen", buurt: ["Venlo","Belfeld","Steyl"]       },
  { slug: "blerick", naam: "Blerick", buurt: ["Venlo","Boekend","Hout-Blerick"] },
  { slug: "belfeld", naam: "Belfeld", buurt: ["Tegelen","Reuver","Steyl"]      },
  { slug: "velden",  naam: "Velden",  buurt: ["Arcen","Lomm","Venlo"]          },
  { slug: "reuver",  naam: "Reuver",  buurt: ["Belfeld","Beesel","Swalmen"]    },
  { slug: "arcen",   naam: "Arcen",   buurt: ["Velden","Lomm","Wellerlooi"]    },
  { slug: "lomm",    naam: "Lomm",    buurt: ["Arcen","Velden","Venlo"]        },
  { slug: "horst",   naam: "Horst",   buurt: ["Sevenum","Venray","Grubbenvorst"] },
  { slug: "sevenum", naam: "Sevenum", buurt: ["Horst","Maasbree","Kronenberg"] },
  { slug: "venray",  naam: "Venray",  buurt: ["Horst","Oostrum","Leunen"]      },
  { slug: "maasbree", naam: "Maasbree", buurt: ["Sevenum","Baarlo","Panningen"] },
  { slug: "panningen", naam: "Panningen", buurt: ["Maasbree","Helden","Egchel"] },
  { slug: "grubbenvorst", naam: "Grubbenvorst", buurt: ["Horst","Lottum","Venlo"] },
  { slug: "baarlo",  naam: "Baarlo",  buurt: ["Maasbree","Kessel","Steyl"]     },
  { slug: "lottum",  naam: "Lottum",  buurt: ["Grubbenvorst","Melderslo","Broekhuizen"] },
];
